"""Canonical BOV approval-domain projections.

Only the projections in this module govern approval validity.  Generated
Office files, timestamps, package metadata, and source-artifact hashes are
deliberately excluded.  Both the approval writer and gate call these same
functions so the trust decision cannot drift between two implementations.
"""

from __future__ import annotations

from typing import Any

from .canonical import canonical_sha256
from .workspace import DealWorkspace


DOMAIN_NAMES = (
    "identity",
    "financial_inputs",
    "pricing_decision",
    "sale_comps",
    "rent_comps",
    "copy",
    "media_selection",
    "regulatory_conclusions",
)


def _take(source: dict[str, Any], *keys: str) -> dict[str, Any]:
    return {key: source.get(key) for key in keys}


def _domain_exceptions(exceptions: dict[str, Any], domain: str) -> list[dict[str, Any]]:
    """Return domain-owned exception decisions in a stable, non-display order.

    Exceptions can authorize otherwise-blocking media or record a material
    financial/identity ruling.  They therefore belong to the domain whose
    meaning they alter.  Sorting by id keeps a harmless note-order change from
    invalidating approval while any substantive exception edit still does.
    """
    return sorted(
        (item for item in exceptions["items"] if item["domain"] == domain),
        key=lambda item: item["id"],
    )


def _deal_presentation_projection(presentation: dict[str, Any]) -> dict[str, Any]:
    """Client-visible deal metadata owned by the identity domain."""
    projection = _take(
        presentation,
        "domain",
        "client",
        "title",
        "subtitle",
        "month_year",
        "cover_label",
        "short_name",
        "city",
        "submarket",
        "parking",
        "team",
        "maps",
    )
    # The declared cluster decides which closings the page counts as this
    # property's local track record, so it is a client-visible claim and
    # belongs in the approved identity hash: declaring one, changing which
    # submarkets it counts, or changing its printed label must all invalidate
    # the approval.
    #
    # ADDED ONLY WHEN PRESENT, never as a null. _take() would serialize the
    # absent default as `track_record_submarkets: null`, which is a DIFFERENT
    # document from the one every already-approved deal hashed. That moved the
    # identity hash of every deal that declares nothing, so check_deal_record()
    # reported `domain invalid: identity` and the production builder refused an
    # otherwise unchanged rebuild. An optional field must be invisible to the
    # hash until it is used.
    group = presentation.get("track_record_submarkets")
    if group is not None:
        projection["track_record_submarkets"] = group
    # Same rule for the Active Listings toggle: it adds or removes an entire
    # client-facing section, so flipping it must invalidate the identity
    # domain and reopen the lead's approval (Codex review on PR #169).
    # Added only when present, for the reason documented above.
    show_listings = presentation.get("show_active_listings")
    if show_listings is not None:
        projection["show_active_listings"] = show_listings
    # Same rule again for Buyout Scenarios, and for its inputs. The toggle adds
    # or removes a client-facing section, and every input is a price the reader
    # sees, so moving one after approval must reopen it. presentation_projections
    # is NOT enough on its own: build_payload regenerates those hashes from the
    # current payload, so an edited assumption produces a fresh matching
    # presentation hash while the canonical domain hash stays untouched
    # (Codex review on PR #254). Added only when present, for the reason above.
    show_buyout = presentation.get("show_buyout_model")
    if show_buyout is not None:
        projection["show_buyout_model"] = show_buyout
    buyout = presentation.get("buyout_model")
    if buyout is not None:
        projection["buyout_model"] = buyout
    return projection


def _semantic_model_projection(model: dict[str, Any]) -> dict[str, Any]:
    """Keep model meaning while excluding raw-file audit metadata.

    Workbook paths, workbook byte hashes, recalculation timestamps, and the
    mechanics used to recalculate are audit/reproducibility fields.  A workbook
    regenerated by Excel with the same recognized structure and outputs must
    not reopen Glen's pricing approval.
    """
    # A land deal carries no M&M model block at all. Project None rather than an
    # empty shape, so the approval hash distinguishes "no template model on this
    # deal" from "a template model whose fields happen to be blank".
    if model is None:
        return None
    return _take(model, "template_id", "named_range_fingerprint", "outputs")


def media_selection_projection(media: dict[str, Any]) -> dict[str, Any]:
    """Project only the approved published selection from a media manifest."""
    items = {item["id"]: item for item in media["archive"]}
    selected = []
    for item_id in media["published"]["order"]:
        item = items.get(item_id)
        if item is None:
            selected.append({"id": item_id, "missing": True})
            continue
        selected.append(
            _take(
                item,
                "id",
                "sha256",
                "phash",
                "category",
                "stock_or_illustrative",
                "property_match",
                "match_basis",
                "publication_basis",
                "usage_scope",
                "required_credit",
                "exception_id",
            )
        )
    return {
        "deal_id": media.get("deal_id"),
        "order": media["published"]["order"],
        "hero": media["published"]["hero"],
        "items": selected,
    }


def project_domains(workspace: DealWorkspace) -> dict[str, Any]:
    deal = workspace.load("deal")
    financials = workspace.load("financials")
    pricing = workspace.load("pricing")
    sale = workspace.load("comps-sale")
    rent = workspace.load("comps-rent")
    copy = workspace.load("copy")
    media = workspace.load("media-manifest")
    exceptions = workspace.load("exceptions")

    projections = {
        "identity": _take(
            deal,
            "document_type",
            "deal_id",
            "slug",
            "seller_side",
            "primary_address",
            "addresses",
            "address_provenance",
            "apns",
            "apn_provenance",
            "unit_count",
            "year_built",
            "building_sf",
            "lot",
            "jurisdiction",
            "rooftop_pin",
            "portfolio_ref",
            "public_names",
            "unit_sf",
        ),
        "financial_inputs": {
            "financials": _take(
                financials,
                "deal_id",
                "currency",
                "tolerances",
                "rent_roll",
                "t12",
                "reconciliations",
                "presentation",
                "exceptions",
            ),
            "approved_operations": pricing.get("operations"),
        },
        "pricing_decision": _take(
            pricing,
            "deal_id",
            "decision",
            "assumptions",
            "sensitivity",
            "risks",
            "what_would_change_it",
            "evidence",
        ),
        "sale_comps": _take(
            sale,
            "deal_id",
            "as_of_date",
            "poison_log_refs",
            "rows",
            "conclusions",
        ),
        "rent_comps": _take(
            rent,
            "deal_id",
            "as_of_date",
            "poison_log_refs",
            "rows",
            "conclusions",
        ),
        "copy": _take(copy, "deal_id", "blocks", "claims"),
        "media_selection": media_selection_projection(media),
        "regulatory_conclusions": {
            "deal_id": deal.get("deal_id"),
            "conclusions": deal.get("regulatory_conclusions"),
        },
    }
    # The decision ledger sets the basis sentence printed beside every income
    # and expense line, so it is a client-visible claim and belongs in the
    # financial-inputs approval: editing a basis must reopen approval the way
    # editing the figure does.
    #
    # ADDED ONLY WHEN PRESENT, never as a null. An unconditional _take would
    # serialize the absent default as `decision_ledger: null`, a different
    # document from the one every already-approved deal hashed, which would
    # move every existing hash and refuse otherwise unchanged rebuilds (the
    # 2026-08-09 track-record-cluster defect, caught in review).
    ledger = financials.get("decision_ledger")
    if ledger is not None:
        projections["financial_inputs"]["financials"]["decision_ledger"] = ledger

    projections["identity"]["presentation"] = _deal_presentation_projection(
        deal["presentation"]
    )
    projections["pricing_decision"]["model"] = _semantic_model_projection(
        pricing["model"]
    )
    projections["media_selection"]["presentation"] = _take(
        deal["presentation"], "no_photo_cover", "hero_tall"
    )
    for domain in DOMAIN_NAMES:
        projections[domain]["exceptions"] = _domain_exceptions(exceptions, domain)
    return projections


def domain_hashes(workspace: DealWorkspace) -> dict[str, str]:
    projections = project_domains(workspace)
    return {name: canonical_sha256(projections[name]) for name in DOMAIN_NAMES}


def portfolio_domain_hashes(
    portfolio: dict[str, Any], member_hashes: dict[str, dict[str, str]]
) -> dict[str, str]:
    """Bind each consolidated domain to the thin index and every member.

    Deal IDs are explicit keys and sorted by canonical serialization.  Moving a
    member's data under another property therefore changes the hash instead of
    permitting silent cross-contamination.
    """
    member_ids = [member["deal_id"] for member in portfolio["members"]]
    if len(member_ids) != len(set(member_ids)):
        raise ValueError("portfolio contains duplicate deal_id values")
    if set(member_hashes) != set(member_ids):
        raise ValueError("portfolio member hashes do not exactly match the thin index")

    presentation = portfolio["presentation"]
    common = {
        "portfolio_id": portfolio["portfolio_id"],
        "members": member_ids,
    }
    domain_context = {
        "identity": {
            "name": portfolio["name"],
            "presentation": _take(
                presentation,
                "domain",
                "client",
                "subtitle",
                "month_year",
                "cover_label",
                "team",
                "portfolio_map",
            ),
        },
        "financial_inputs": {},
        "pricing_decision": {
            "portfolio_price": portfolio.get("portfolio_price"),
            "portfolio_price_basis": portfolio.get("portfolio_price_basis"),
        },
        "sale_comps": {},
        "rent_comps": {},
        "copy": {},
        "media_selection": {
            "hero_member": presentation["hero_member"],
            "hero_media_id": presentation["hero_media_id"],
            "hero_tall": presentation.get("hero_tall"),
        },
        "regulatory_conclusions": {},
    }
    return {
        domain: canonical_sha256(
            {
                "portfolio": {**common, **domain_context[domain]},
                "members": {
                    deal_id: member_hashes[deal_id][domain]
                    for deal_id in sorted(member_ids)
                },
            }
        )
        for domain in DOMAIN_NAMES
    }
